name: first workflow
on: workflow_dispatch
jobs:
  first_job: 
    runs_on: ubuntu-latest
    steps:
      - name: afficher bonjour
        run: echo "salut tout le monde"
      - name: dire good luck
        run: echo "good luck"
